version: '3'
services:
  api:
    image: price-predictor:latest
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 